spring:
  datasource:
    url: jdbc:mysql:///sdhy-bs-boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: xxxxxxxxx
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    static-path-pattern: /static/**/**

  thymeleaf:
    cache: false
